baseURL = 'https://g-snipes.github.io/'
languageCode = 'en-us'
title = 'G Snipe Site'

[author]
  name = "Gary"

theme = ["github.com/jpanther/congo/v2"]

[module]
  [[module.imports]]
    path = "github.com/jpanther/congo/v2"