languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = ""
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  isoCode = "en"
  displayName = "EN"
  rtl = false
  dateFormat = "2 January 2006"

  description = "G Snipe personal website. I offer creative services and blog everything from underground bands, to tech rabbit holes, to global affairs, I got it all. And more wierd stuff. (Interviews, Show Recaps, Journal Entries, Tech, Blog, Blogposts, Music Videos, Services)"
  mainSections = ["blog"]
  # description = "G Snipe personal website"

[params.author]
  name = "Gary Snipes"
  image = "img/mainphoto.png"
  headline = "Artist"
  bio = "I make stuff."
  links = [
  #   { email = "gsnipe721@gmail.com" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
  #   { google-scholar = "https://scholar.google.com/citations?user=user-id" },
  #   { hashnode = "https://username.hashnode.dev" },
      { youtube = "https://www.youtube.com/@g_snipe?sub_confirmation=1" },
      { instagram = "https://www.instagram.com/g_snipe_/" },
      { bluesky = "https://bsky.app/profile/g-snipe.bsky.social" },
      { discord = "https://discord.gg/7a6X2Ffn" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { mendeley = "https://www.mendeley.com/" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { threads = "https://threads.net/@username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
      { kofi = "https://ko-fi.com/gsnipe" },
  #   { linkedin = "https://www.linkedin.com/in/gary-snipes-07b6821b9/" },
  #   { soundcloud = "https://soundcloud.com/gary-snipes-911910897" },
  #   { github = "https://github.com/G-Snipes" },
  #   { x-twitter = "https://x.com/GSnipe_" },
  ]