# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.


[[main]]
  name = "GitHub"
  url = "https://github.com/G-Snipes"
  weight = 5
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"

 [[main]]
  name = "YouTube"
  url = "https://www.youtube.com/channel/UCeSCs3awP_eWH0TwvqH4j9Q"
  weight = 6
  [main.params]
    icon = "youtube"
    showName = false
    target = "_blank"

[[main]]
  name = "Services"
  pageRef = "categories"
  weight = 10

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 30

[[main]]
  name = "Contact"
  pageRef = "posts"
  weight = 20

[[main]]
  name = ""
  identifier = "search"
  weight = 100
  [main.params]
    action = "search"
    icon = "search"

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

[[footer]]
  name = ""
  identifier = "appearance"
  weight = 31
  [footer.params]
    action = "appearance"
    icon = "lightbulb"
