name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main # Or 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.127.0' # Or your desired version
          extended: true
          
      # --- NEW STEP: Aggressive cleanup ---
      - name: Ensure themes/congo is completely gone
        run: |
          echo "Attempting to remove themes/congo directory (if any lingering remnants exist)."
          rm -rf themes/congo
          echo "Listing themes/ after cleanup attempt:"
          ls -al themes/ || true # Use || true so this command doesn't fail the job if 'themes/' is empty
          echo "Cleanup attempt complete."

      - name: Initialize Hugo Modules
        run: hugo mod tidy # This command should now successfully download the theme

      - name: Build site
        run: hugo --minify --cleanDestinationDir

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          force_orphan: true