name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main # Or 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- MODIFIED STEP: More aggressive cleanup and .gitmodules check ---
      - name: Ensure themes/ directory state and check .gitmodules
        run: |
          echo "Attempting to remove entire themes/ directory to ensure no remnants."
          rm -rf themes/ # Remove the entire themes directory
          echo "Listing themes/ after aggressive removal (should be empty or non-existent):"
          ls -al themes/ || echo "themes/ directory is gone or empty (expected)."

          echo "--- Checking .gitmodules file ---"
          cat .gitmodules || echo ".gitmodules not found (this is desired for Hugo Modules)."
          echo "--- End .gitmodules check ---"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.127.0'
          extended: true

      - name: Clean Hugo Modules Cache
        run: hugo mod clean || true

      - name: Explicitly Get Theme Module
        # KEEP THIS AS ANANKE for now, until it works, then switch back to Congo
        run: hugo mod get github.com/theNewDynamic/gohugo-theme-ananke/v2

      - name: Build site
        # Keep 'theme = "ananke"' in config.toml for this test
        run: hugo --minify --cleanDestinationDir

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          force_orphan: true