name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main # Or 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure themes/congo is completely gone
        run: |
          echo "Attempting to remove themes/congo directory (if any lingering remnants exist)."
          rm -rf themes/congo
          echo "Listing themes/ after cleanup attempt:"
          ls -al themes/ || true
          echo "Cleanup attempt complete."

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.127.0' # Or your desired version
          extended: true

      - name: Clean Hugo Modules Cache
        run: hugo mod clean || true # Keep || true so it doesn't stop the workflow if it still hits the error.

      # --- NEW STEP: Explicitly Get Congo Module ---
      - name: Explicitly Get Congo Theme Module
        run: hugo mod get github.com/jpanther/congo/v2
        # This forces Hugo to download the module from the specified path.

      - name: Build site
        run: hugo --minify --cleanDestinationDir # Keep theme commented out for now

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          force_orphan: true
          