# .github/workflows/gh-pages.yml

name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Force clean repository
        run: |
          git clean -dfx # Removes all untracked files and directories
          git reset --hard HEAD # Ensures working directory matches the last commit

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.145.0"
          extended: true

      - name: Debug List theme contents
        run: |
          echo "Listing contents of 'themes/' directory:"
          ls -alR themes/ # List all files and directories recursively
          echo "Checking specific partial file:"
          ls -l themes/congo/layouts/partials/functions/warnings.html || echo "warnings.html not found at expected path"
          echo "Permissions for themes/congo/layouts/partials/functions/:"
          ls -ld themes/congo/layouts/partials/functions/
          echo "Permissions for themes/congo/layouts/partials/:"
          ls -ld themes/congo/layouts/partials/
          echo "Permissions for themes/congo/layouts/:"
          ls -ld themes/congo/layouts/
      
      - name: Build
        run: hugo --minify --themesDir themes

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
